# Installing torch through conda env will not work will installing cudatoolkit at the same time
name: mlenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - conda-forge::cudatoolkit=11.3
  - conda-forge::opencv
  - conda-forge::pyyaml
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::jupyterlab
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::pillow
  - conda-forge::mpi4py
  - conda-forge::tensorboard
  - conda-forge::dill
  - conda-forge::psutil
  - conda-forge::rich
  - pip:
    - torch
    - torchvision
    - hydra-core
