name: mlenv
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pip
  - conda-forge::opencv
  - conda-forge::pyyaml
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::jupyterlab
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::scipy=1.9.1 # Prevent Sklearn `GLIBCXX_3.4.30' not found error
  - conda-forge::scikit-learn=1.1.3 
  - conda-forge::mpi4py
  - conda-forge::dill
  - conda-forge::psutil
  - pip:
    - tensorflow
    - tensorboard
    - hydra-core