name: mlenv
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pip
  - conda-forge::gxx_linux-64
  - conda-forge::cmake
  - conda-forge::make
  - conda-forge::libstdcxx-ng
  - conda-forge::importlib_metadata
  - conda-forge::cudatoolkit
  - conda-forge::opencv
  - conda-forge::pyyaml
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::jupyterlab
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::scipy
  - conda-forge::scikit-learn=1.0.2
  # Sklearn depend
  - libgcc
  - conda-forge::mpi4py
  - conda-forge::dill
  - conda-forge::psutil
  - pip:
    - tensorflow-gpu
    - tensorboard
    - hydra-core